# TODO cache?
name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: wipop
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies and run tests
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
              npm ci
            else
              npm install
            fi  
          npm ci
          npm test --if-present

      - name: Build plugin without tests and so
        run: |
          npm run build
          cd ..
          zip -r wipop.zip wipop \
            -x "wipop/src/*" \
            -x "wipop/node_modules/*" \
            -x "wipop/tests/*" \
            -x "wipop/.*"

      - name: Switch to Node 20 for Semantic Release
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
